services:
  postgres-db:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=w1dataengi
      - POSTGRES_PASSWORD=w1d@taengi
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  postgres-ui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=w1@dataengi.com
      - PGADMIN_DEFAULT_PASSWORD=w1dataengi
    ports:
      - 8080:80