services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: kestr5-user
      POSTGRES_PASSWORD: k3sTR5
      POSTGRES_DB: postgres-zoomcamp-w2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres-ui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=w2@dataengi.com
      - PGADMIN_DEFAULT_PASSWORD=w2dataengi
    ports:
      - 8082:80
volumes:
  postgres-data: